/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ICashManager, ICashManagerInterface } from '../../../contracts/interfaces/ICashManager';

const _abi = [
    {
        inputs: [],
        name: 'buy',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            {
                internalType: 'bytes4',
                name: 'interfaceId',
                type: 'bytes4',
            },
        ],
        name: 'supportsInterface',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: 'amount',
                type: 'uint256',
            },
        ],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
];

export class ICashManager__factory {
    static readonly abi = _abi;
    static createInterface(): ICashManagerInterface {
        return new utils.Interface(_abi) as ICashManagerInterface;
    }
    static connect(address: string, signerOrProvider: Signer | Provider): ICashManager {
        return new Contract(address, _abi, signerOrProvider) as ICashManager;
    }
}
