/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as escrow from './escrow';
export type { escrow };
import type * as introspection from './introspection';
export type { introspection };
export type { ContextUpgradeable } from './ContextUpgradeable';
