/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICash } from "./ICash";
export type { ICashManager } from "./ICashManager";
export type { ITicket } from "./ITicket";
export type { ITicketManager } from "./ITicketManager";
