/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces';
export type { interfaces };
export type { Cash } from './Cash';
export type { CashManager } from './CashManager';
export type { EvenOdd } from './EvenOdd';
export type { Ticket } from './Ticket';
export type { TicketManager } from './TicketManager';
